---
task:
  - name: Add debian unstable repository (wireguard)
    apt_repository: 
      repo: deb http://deb.debian.org/debian/ unstable main
      state: present
  - name: limit unstable repository priority
    template:
      dest: /etc/apt/preferences.d/limit-unstable
      src: apt_unstable.j2
  - name: install wireguard
    apt:
      name: wireguard
      state: latest
      default_release: unstable
      update_cache: yes
  hosts: all
 
